spring:
  application:
    name: sis-redirect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
sis-redirect:
  version: @app.version@
  env: ${app.env}

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m
